# from config import db, app
# from models import User, Song, Genre, FormPost

# with app.app_context():
#     db.session.add(Genre(name="Hip hop music"))
#     db.session.add(Genre(name="Rock"))
#     db.session.add(Genre(name="Country music"))
#     db.session.add(Genre(name="Pop music"))
#     db.session.add(Genre(name="Indie rock"))
#     db.session.add(Genre(name="Jazz"))
#     db.session.add(Genre(name="Heavy metal"))
#     db.session.add(Genre(name="Techno"))
#     db.session.add(Genre(name="Alternative rock"))
#     db.session.add(Genre(name="Dubstep"))
#     db.session.add(Genre(name="Blues"))
#     db.session.add(Genre(name="R&B"))
#     db.session.add(Genre(name="Reggae"))
#     db.session.add(Genre(name="Classical music"))
#     db.session.add(Genre(name="Electronic music"))
#     db.session.add(Genre(name="Trap music"))
#     db.session.add(Genre(name="Electronic dance music"))
#     db.session.add(Genre(name="Ambient"))
#     db.session.add(Genre(name="Emo"))
#     db.session.add(Genre(name="Hard rock"))
#     db.session.add(Genre(name="Pop rap"))
#     db.session.add(Genre(name="K-pop"))
#     db.session.add(Genre(name="New-age music"))
#     db.session.add(Genre(name="New wave"))
#     db.session.commit()