"""added al cov

Revision ID: 09310d9df30a
Revises: 01d649c14379
Create Date: 2023-05-11 12:42:55.163098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09310d9df30a'
down_revision = '01d649c14379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album_cover', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('album_cover')

    # ### end Alembic commands ###
