"""added username

Revision ID: bc2c7ee31a0c
Revises: 09310d9df30a
Create Date: 2023-05-11 21:44:15.863871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2c7ee31a0c'
down_revision = '09310d9df30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_posts', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
